// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.920
package main

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Index() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"card lg:card-side shadow-sm h-140\"><div class=\"card-body items-center text-center justify-center bg-image\"><article class=\"prose lg:prose-m py-4 w-full text-light-blue\"><h1 class=\"text-4xl\">Welcome to</h1><h1 class=\"text-6xl\">My Chicago Therapy</h1><p class=\"text-xl\">Your space for healing, growth, and connection.</p></article></div></div><div class=\"card lg:card-side shadow-sm h-150\"><figure class=\"w-180\"><img loading=\"lazy\" alt=\"Jeremy Dales\" src=\"images/jeremy.png\"></figure><div class=\"card-body p-10 bg-light-brown text-light-blue flex justify-center shadow-sm\"><article class=\"prose prose-slate lg:prose-lg max-w-3xl m-8\"><h1 class=\"card-title text-2xl font-bold mb-6\">Great to meet you!</h1><p class=\"text-lg\">Life can be <span class=\"underline decoration-light-blue font-semibold\">messy</span>, and baggage can accumulate until we're barely able to function.</p><p class=\"text-lg\">If that sounds familiar, I want you to know that <span class=\"underline decoration-light-blue font-bold\">you deserve better</span>.</p><p class=\"text-lg\">You deserve a life where you can <span class=\"decoration-light-blue font-semibold\">express who you are</span>, <span class=\"decoration-light-blue font-semibold\">support your family and friends</span>, and <span class=\"decoration-light-blue font-semibold\">be a productive member of society</span>.</p><p class=\"text-lg\">Regardless of what you've experienced in your life, <span class=\"underline decoration-light-blue font-bold\">you deserve a better life</span>.</p><p class=\"text-lg\">I am a Clinical Social Worker with over 10 years of experience working in a wide range of settings,</p><p class=\"text-lg\">including inpatient adolescent care, Veteran's Services, and private practice.</p></article></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = Page().Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
